on:
  push:
    branches:
      - main

jobs:
  included:
    uses: ./.github/workflows/include.yaml

  third:
    runs-on: debian

    needs:
      - included

    steps:
      - name: Step three
        run: echo "Step three"

  fourth:
    runs-on: debian

    needs:
      - third

    steps:
      - name: Step four
        run: echo "Step four"
